### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by dragstor** [smileshey/TransitCostEstimator#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://buildmoretrains.streamlit.app/smileshey/transitcostestimator/streamlit/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by smileshey** [comment]
I appreciate it. I missed this at the time, but I reset the site and it should be working fine until the resource limit gets hit again soon :)
